services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-server
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - TZ=Asia/Seoul
    volumes:
      - /app/docker/mariadb_data:/var/lib/mysql

  backend:
    build:
      context: ../backend
      dockerfile: ../docker/backend/Dockerfile
    container_name: salon-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://root:password@mariadb:3306/salon_db
      - TZ=Asia/Seoul
      - JWT_SECRET=salon_manager_secret_key
      - JWT_EXPIRATION_TIME=3600s
      - JWT_REFRESH_SECRET=salon_manager_refresh_secret_key
      - JWT_REFRESH_EXPIRATION_TIME=604800s
    depends_on:
      - mariadb
    volumes:
      - ./uploads:/app/uploads

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile
    container_name: salon-frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
